// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialBuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialBuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201311040156507_InitialBuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
