// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLogging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLogging));
        
        string IMigrationMetadata.Id
        {
            get { return "201311080311342_AddLogging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
